# LAB 09 - 데이터 베이스 프로그래밍

## 데이터 베이스 접속하기
### 단일행 데이터 조회

In [9]:
from sqlalchemy import create_engine,text
from pandas import DataFrame

### 접속 문자열 생성 
mariadb+pymysql://계정이름:비밀번호@서버주소:포트/데이터베이스?charset=utf8mb4
SQLAlchemy 에서 요구하는 형식의 문자열을 생성한다

In [10]:
config = {
  'username' : 'root',
  'password':'1234',
  "hostname":'localhost',
  'port':9090,
  'database':'myschool',
  'charset' : 'utf8mb4'

}


con_str_tpl ="mariadb+pymysql://{username}:{password}@{hostname}:{port}/{database}?charset={charset}"

con_str=con_str_tpl.format(**config)
print(con_str)

mariadb+pymysql://root:1234@localhost:9090/myschool?charset=utf8mb4

### SQL 실행 객체 생성
데이터 베이스에 접속하여 SQL 실행 객체를 생성한다

In [ ]:
try:
  #con_str 은 직전 블록에서 생성한 변수를 재사용하고 있음
  engine =create_engine(con_str)
  # 데이터 베이스에 접속하여 sql 실행 객체를 리턴받는다
  conn=engine.connect()
  print("Database connect success!!!")

except Exception as e:
  #예외 발생 시 에러 메세지를 참고하여 접속 정보를 확인한다
  print("Database connect fail!!!",e)

Database connect success!!!

### 단 하나의 행을 조회하는 SQL 문 실행하기

In [ ]:
#sql 문을 정의한다
sql = text ("Select id, name , grade, department_id  FROM STUDENTS WHERE ID =10101")

try:
  #sql 문을 싱행하여 결과 객체를 받는다
  result = conn.execute(sql)

except Exception as e:
  print(["SQL Error",e])
  raise SystemExit


# sql 문 실행 결과를  딕셔너리를 포함하는 리스트 형태로 변환한다
#mappings()은 SQLAlchemy의 Result 객체를 딕셔너리 형태로 접근할 수 있도록 바꿔주는 메서드
# all 은 결과 전체를 한번에 리스트로 변환
# 즉 mapping() 는 각 행을 딕셔너리로 바꾸고, all() 은 그 행들을 리스트로 묶어준다
resultset = result.mappings().all()
print(resultset)

[{'id': 10101, 'name': '황진우', 'grade': 1, 'department_id': 101}]

### 형식 문자를 포함하는 SQL 실행

In [17]:
#검색할 조건값 입력받기
student_id = input("검색할 학번을 입력하세요")

# SQL 문 정의 -> 변수의 치환할 부분을 ':변수명' 형식으로 처리
#             -> 치환될 문자가 문자열이더라도 홑따옴표 사용 하지 않음

sql = text ("SELECT id, name, grade , department_id from students where id = :student_id")

#SQL 문의 물음표를 치환할 값을 딕셔너리로 묶음 ( 물음표 순서에 따라 조합)
params = {'student_id':student_id}



try:
  #SQL 문을 실행하여 결과 객체 받기 > 치환할 값에 대한 딕셔너리도 함께 전달
  result = conn.execute(sql,params)

except Exception as e:
  print("[SQL Error]" ,e)

  # 코드의 진행을 중단시킴
  raise SystemExit

# 단일행 조회에 대한 결과 집합 추출하기
#기본적으로 RESULT 는 튜플 형식인데, 각 컬럼명과 매핑해서 딕셔너리로 만들고, 그걸 다시 리스트로 반환
resultset = result.mappings().all()
print(resultset)

[]

### 다중행 데이터 조회
여러 행을 반환하는 sql 문을 실행해보자

In [20]:
sql = text ("SELECT id ,dname, loc, phone, email from departments limit 0,5")

try:
  result = conn.execute(sql)

except Exception as e:
  print("[SQL Error]",e)
  raise SystemExit

resultset = result.mappings().all()
print(resultset)

[{'id': 101, 'dname': '컴퓨터공학과', 'loc': '공학관', 'phone': '051-123-4567', 'email': 'cs@myschool.ac.kr'}, {'id': 102, 'dname': '소프트웨어학과', 'loc': '공학관', 'phone': '051-124-4567', 'email': 'media@myschool.ac.kr'}, {'id': 201, 'dname': '전자공학과', 'loc': '공학관', 'phone': '051-125-4567', 'email': 'ee@myschool.ac.kr'}, {'id': 202, 'dname': '기계공학과', 'loc': '공학관', 'phone': '051-126-4567', 'email': 'me@myschool.ac.kr'}, {'id': 203, 'dname': '건축학과', 'loc': '건축관', 'phone': '051-127-4567', 'email': 'arch@myschool.ac.kr'}]

### 결과 집합 사용하기
### 반복문을 활용한 데이터 출력
결과 집합은 딕셔너리를 포함하는 리스트 형식으로 반환되므로 이를 반복문으로 출력할 수 있다

In [22]:
print("총 %d 건의 데이터 조회됨 % len(resultset)")

tmpl ="학과번호:{id} , 학과이름: {dname}, 위치 {loc} ,연락처 : {phone}, 이메일 : {email}"


for row in resultset:
  print(tmpl.format(**row))

총 %d 건의 데이터 조회됨 % len(resultset)
학과번호:101 , 학과이름: 컴퓨터공학과, 위치 공학관 ,연락처 : 051-123-4567, 이메일 : cs@myschool.ac.kr
학과번호:102 , 학과이름: 소프트웨어학과, 위치 공학관 ,연락처 : 051-124-4567, 이메일 : media@myschool.ac.kr
학과번호:201 , 학과이름: 전자공학과, 위치 공학관 ,연락처 : 051-125-4567, 이메일 : ee@myschool.ac.kr
학과번호:202 , 학과이름: 기계공학과, 위치 공학관 ,연락처 : 051-126-4567, 이메일 : me@myschool.ac.kr
학과번호:203 , 학과이름: 건축학과, 위치 건축관 ,연락처 : 051-127-4567, 이메일 : arch@myschool.ac.kr

### 결과 집합을 표 형태로 변환
pandas 라이브러리에 포함되어 있는 dataframe클래스는 '딕셔너리를 포함하는 리스트' 를 생성자 파라미터로 전달받아서 이를 표로 변환하여 리턴한다

In [24]:
df1 = DataFrame(resultset)

print(df1)

     dname                 email   id  loc         phone
0   컴퓨터공학과     cs@myschool.ac.kr  101  공학관  051-123-4567
1  소프트웨어학과  media@myschool.ac.kr  102  공학관  051-124-4567
2    전자공학과     ee@myschool.ac.kr  201  공학관  051-125-4567
3    기계공학과     me@myschool.ac.kr  202  공학관  051-126-4567
4     건축학과   arch@myschool.ac.kr  203  건축관  051-127-4567

### 주피터의 고유 기능을 활용하여 표 형태로 출력하기
주피터는 print() 함수 없이 변수나 객체 이름만 명시하여도 이를 출력하는 기능을 제공한다

In [26]:
df2=DataFrame(resultset)
df2

     dname                 email   id  loc         phone
0   컴퓨터공학과     cs@myschool.ac.kr  101  공학관  051-123-4567
1  소프트웨어학과  media@myschool.ac.kr  102  공학관  051-124-4567
2    전자공학과     ee@myschool.ac.kr  201  공학관  051-125-4567
3    기계공학과     me@myschool.ac.kr  202  공학관  051-126-4567
4     건축학과   arch@myschool.ac.kr  203  건축관  051-127-4567

### 입력값에 따른 검색 결과 만들기

In [34]:
keyword = input("검색할 교수 이름을 입력하세요")

sql =text (
'''select p.id as 교수번호 , position as 직급 , sal as 급여, comm as 보직수당 , hiredate as
입사일시 ,dname as 소속학과 from professors p inner join departments d on p.department_id = d.id
where name like concat("%",:keyword,"%")
'''
)

try:
  result = conn.execute(sql,{"keyword": keyword})

except Exception as e:
  print("SQL Error", e)
  raise SystemExit


resultset = result.mappings().all()
df = DataFrame(resultset)
df

Empty DataFrame
Columns: []
Index: []

### 데이터 입력하기

In [ ]:
# 데이터를 저장하기 위한 SQL문 템플릿 구성
sql = text("""
    INSERT INTO students (
        name, user_id, grade, idnum, birthdate, phone, height,
        weight, email, gender, status, admission_date, department_id
    ) VALUES (
        :name, :user_id, :grade, MD5(:idnum), :birthdate, :phone, :height,
        :weight, :email, :gender, :status, :admission_date, :department_id
    )
""")

# SQL문에 치환할 실제 값
new_student = {
    "name": "나신입",
    "user_id": "newbie",
    "grade": 1,
    "idnum": "9205171000000",
    "birthdate": "2024-03-15",
    "phone": "010-9876-5432",
    "height": 175,
    "weight": 82,
    "email": "newbie@myschool.ac.kr",
    "gender": "남",
    "status": "재학",
    "admission_date": "2028-02-12",
    "department_id": 101
}


try:
    # SQL문 실행하기 -> 자동 트랜잭션
    result = conn.execute(sql, new_student)
    affected_rows = result.rowcount        # 저장된 행의 수 확인
    conn.commit()                          # 변경사항을 DB에 실제 반영

    # 생성된 PK값(Primary Key) 추출하기
    pk_result = conn.execute(text("SELECT LAST_INSERT_ID()"))
    pk = pk_result.scalar()                # 단일값(= 새로 생성된 ID)만 추출

except Exception as e:
    print("SQL Error:", e)
    conn.rollback()                        # 오류 발생 시 변경사항 되돌리기
    raise SystemExit                       # 프로그램 종료

# INSERT문 실행 결과 확인
print("저장된 행의 수:", affected_rows, ", 신규 학생 ID:", pk)

### 데이터 수정하기

In [ ]:
# 특정 학생의 연락처와 이메일 수정하기
sql = text("UPDATE students SET phone = :phone, email = :email WHERE id = :id")

# 수정할 데이터 준비
params = {
    "phone": "010-1234-5678",
    "email": "jinwoo.h@myschool.ac.kr",
    "id": 10102
}

# SQL문 실행하기
try:
    result = conn.execute(sql, params)
    conn.commit()
except Exception as e:
    print(f"데이터 수정 오류: {e}")
    conn.rollback()
    raise SystemExit

print("수정된 데이터 수:", result.rowcount)

### 데이터 삭제하기

In [35]:
# 특정 학생 수강내역 삭제하기
sql = text("DELETE FROM enrollments WHERE student_id = :id")

# 삭제할 데이터 준비
params = {"id": 10102}

# SQL문 실행하기
try:
    result = conn.execute(sql, params)
    conn.commit()
except Exception as e:
    print(f"데이터 삭제 오류: {e}")
    conn.rollback()
    raise SystemExit

print("삭제된 데이터 수:", result.rowcount)

삭제된 데이터 수: 2

## Pandas 활용 데이터 조회
### 기본 데이터 조회

In [37]:
#sql 문의 결과를 표 형태로 직접 가져오기
from pandas import read_sql

sql = text("select id,name,position,sal,comm from professors where sal>500")


try:
  df=read_sql(sql,conn)

except Exception as e:
  print("SQL Error",e)
  raise SystemExit

df

     id name position  sal  comm
0  9902  허경희     전임강사  552   NaN
1  9903  전종수      조교수  508   NaN
2  9910  강영호      조교수  593   NaN
3  9915  이옥순       교수  548  22.0
4  9918  오미영      부교수  578   NaN
5  9928  이영길      조교수  526  14.0
6  9931  박태수      부교수  510   NaN
7  9932  최정훈      부교수  520   NaN
8  9933  최정훈      부교수  520   NaN

In [ ]:
# 검색 조건을 입력 받아서 직업 가져오기


min_height = int(input('키워 하한값을 입력하세요'))
max_height = int(input("키의 상한값을 입력하세요"))

sql = text("""
select id,name,grade,height, weight, gender from students where height between :min and :max


"""
           )



try:
  df = read_Sql(sql,conn,params={"min":min_height , "max":max_height})

except Exception as e:
  print("SQL Error:",e)
  raise SystemExit


df